// Auto-generated language modules
// Generated by tools/migration/codegen.rs

pub mod af;
// pub mod ar;  // TODO: Fix dictionary errors
pub mod bg;
pub mod bn;
pub mod ca;
pub mod cs;
pub mod da;
pub mod de;
pub mod el;
pub mod en;
pub mod es;
pub mod et;
pub mod fa;
pub mod fi;
pub mod fr;
pub mod ga;
pub mod he;
pub mod hi;
pub mod hr;
pub mod hu;
pub mod id;
pub mod is;
pub mod it;
pub mod ja;
pub mod ka;
// pub mod km;  // TODO: Fix dictionary errors
pub mod kn;
// pub mod ko;  // TODO: Fix dictionary errors
pub mod lo;
pub mod ml;
pub mod mn;
pub mod my;
pub mod nb;
pub mod ne;
pub mod nl;
pub mod pl;
pub mod pt;
// pub mod ro;  // TODO: Fix character escape errors (\537)
pub mod ru;
pub mod sk;
pub mod sv;
pub mod sw;
pub mod ta;
pub mod te;
pub mod th;
// pub mod tr;  // TODO: Fix type errors
pub mod uk;
pub mod unknown;
// pub mod vi;  // TODO: Fix dictionary errors
pub mod zh;
