// Auto-generated language modules
// Generated by tools/migration/codegen.rs

pub mod af;
pub mod ar;  // ✅ Phase B: Dictionary from Helpers.hs extracted
pub mod bg;
pub mod bn;
pub mod ca;
pub mod cs;
pub mod da;
pub mod de;
pub mod el;
pub mod en;
pub mod es;
pub mod et;
pub mod fa;
pub mod fi;
pub mod fr;
pub mod ga;
pub mod he;
pub mod hi;
pub mod hr;
pub mod hu;
pub mod id;
pub mod is;
pub mod it;
pub mod ja;
pub mod km;  // ✅ Phase B: Multi-line comment support in HashMap extraction
pub mod ka;
pub mod kn;
pub mod ko;  // ✅ Phase B: Multiple dict references extracted
pub mod lo;
pub mod ml;
pub mod mn;
pub mod my;
pub mod nb;
pub mod ne;
pub mod nl;
pub mod pl;
pub mod pt;
pub mod ru;
pub mod sk;
pub mod sv;
pub mod sw;
pub mod ta;
pub mod te;
pub mod th;
pub mod uk;
pub mod vi;  // ✅ Phase B: Dictionary references fixed
pub mod unknown;
pub mod zh;
