// Language modules
// Auto-generated by tools/migration/codegen.rs
// Manually maintained for pilot languages (en, zh, es, fr, de, it)

pub mod de;
pub mod en;
pub mod es;
pub mod fr;
pub mod it;
pub mod nb;
pub mod zh;
